### ISSUE TITLE
Netherite pickaxe bonus drops don't work

### ISSUE THREAD

**Issue by wingzero54** [CivMC/HiddenOre#12]
Player reported issue, netherite pickaxes are configured to give additional drops but this doesn't appear to be working. 

Will need to check and verify the private config and also troubleshoot if it works in general and is just a config issue, or whether there is an issue with the mechanic.

**Comment by quinn404** [comment]
bit of a sanity check but did you add both the normal stone ores and the deepslate ores to the extra drops config?

if it were the case that it was just the normal stone ores then that might explain why people are breaking the mostly deepslate diamond ores and not getting any extra

**Comment by quinn404** [comment]
missclick sorry

**Comment by wingzero54** [comment]
I think you're right, they appear to be missing the line below, I'll need to test and confirm this fixes it

      tools:
       - netherite_pickaxe

**Comment by wingzero54** [comment]
Needs more testing, I haven't been able to figure out why this isn't working. I tried adding the above line but it didn't seem to work still
