### ISSUE TITLE
Update from legacy material handling

### ISSUE THREAD

**Issue by wingzero54** [CivMC/HiddenOre#14]
HiddenOre uses legacy bukkit methods which are deprecated and cause us tons of headaches (we have to specify a version number for every material in the hiddenore config or it just doesn't work). Below is the error it provides on legacy material support, and an example of the error we get for null materials if we don't get the material version correct

[Server thread/ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[Server thread/ERROR]: [org.bukkit.configuration.serialization.ConfigurationSerialization] Could not call method 'public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserialize(java.util.Map)' of class org.bukkit.inventory.ItemStack for deserialization
java.lang.IllegalArgumentException: Material cannot be null

**Comment by ProgrammerDan** [comment]
the legacy mode is activated b/c you are missing a version specifier.

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemStack.html#deserialize(java.util.Map)

the underlying spigot method is NOT deprecated or legacy, just your configuration.

Refresh your configuration by using /serialize command in SAH while holding the intended block; it will generate an up-to-date version of the block data.

please don't replace this non-custom -- uses standardized serialization -- code with some civ-style janky items loader. Serialize / deserialize is just the standard spigot method, and not deprecated.
