### ISSUE TITLE
HiddenOre Ignores Y levels below 1

### ISSUE THREAD

**Issue by OwainX** [CivMC/HiddenOre#5]
Issue with ore replacement /clearing on chunk generation in 1.18 as it appears the Y level of the bottom of the world is hardcoded.  In WorldGenerationListener.java changing the chunk processing to the following changes to floor level to -64.  May be a better solution but this does seem to work.

`			// now scan the chunk for ores and remove them.
			for (int y = 1; y < (maxY + 64); y++) {
				for (int x = 0; x < 16; x++) {
					for (int z = 0; z < 16; z++) {
						Block block = chunk.getBlock(x, (y - 64), z);`

**Comment by wingzero54** [comment]
@OwainX if you didn't see, this was resolved with Diet's mentioned PR
